### ISSUE TITLE
What is needed for better Automation in CI/CD

### ISSUE THREAD

**Issue by SebastianSchuetze** [SharePoint/sp-dev-build-extensions#16]
Hi,

I wanted to ask what would be needed. I could contribute several things. But I would like to know if this is wanted / needed

- Yaml script for build for SharePoint Solutions, AddIns, SPFx solutions
- Exported JSON files for CI / CD to import in VSTS for SharePoint Solutions, AddIns, SPFx solutions
- Guidelines for Tipps and Tricks to deploy SharePoint Solutions with VSTS
- Guidelines for using SharePoint ALM API with VSTS
- Example Project for Serverless Computing (Azure Function) which uses the Graph API and / or SharePoint API (with ARM Template, Sample Code and Guideline)

I think I can think of more. But would this be needed?

Thanks for feedback in advance. :-)

**Comment by SebastianSchuetze** [comment]
@wobba @estruyf hi guys. I guess nobody is monitoring the issue part here. Vesa gave me this repository for contribution. Some feed would be very much appreciated, then I could start creating some code.

**Comment by wobba** [comment]
Hi,
Guidance on CI/CD using VSTS would probably be useful. I would probably author it first and then possibly add it into the spfx docs as an article PR. If you think something is missing which is not a blog post, propose an outline and check if it's a fit.

As for other samples you can create PR's you see useful, or again do an outline and ask before doing it.

What do you think would be useful for the community and in what format? :)

**Comment by baywet** [comment]
Hey @SebastianSchuetze thanks for mentioning it. I owed a PR to @VesaJuvonen for a long time now… checkout #17 and #18 and don't hesitate to provide feedback!.
Once we get the repository started it'll be easier to have everybody contribute and add more tools and samples

**Comment by SebastianSchuetze** [comment]
@VesaJuvonen question: are provider hosted apps needed as samples? I could make a sample app with a azure app service as a resource and have everything prepared for deployment with Azure DevOps. I could also write an article with that.

**Comment by baywet** [comment]
I don't think we have a roadmap at the moment, it'd be nice to work on a list collaboratively. I was thinking maybe about Jenkins, circle ci, appveyor for spfx. And yeah we probably need to add some content for the addins as well. I can probably dig some old content from my blog for those.
How do you suggest we coordinate? I started creating issues for missing stuff

**Comment by SebastianSchuetze** [comment]
If you could digg up a sample application for an addin in. I would really much like to take care of a pipeline with yaml and a json export. Also a docs page as well.

I am pretty new how on GitHub open source. I have no structure how to start. Any idea on where to put a roadmap or where to put what, I would suggest, I would follow you way of doing it.

**Comment by baywet** [comment]
Usually the way it's done is you opened detailed "issues" for each thing you want to accomplish, then you can do two things: 
- assign them to people to work on
- group them together in a planned release.
The only thing it that you need to be admin of the github repos to set these up and I think today Vesa is the only admin and he has many other things to deal with. Maybe one of us should get/request for ownership of the repo

**Comment by baywet** [comment]
On the add-ins thing, yes this is needed by the community I'm not sure how we should prioritize things. On my end I'm not touching those anymore for a long time at work. So it's probably best if somebody else takes care of it. (but let's start by creating a separate issue)

**Comment by SebastianSchuetze** [comment]
I could take care of the solution. How complex should the sample be? I mean to start with any sample just to get a best practice CD / CI sample is easy. I am just not sure if a provider hosted "hello world" addin-in would be enough.
