### ISSUE TITLE
Build Pipeline: gulp file path does not reflect repository structure

### ISSUE THREAD

**Issue by SebastianSchuetze** [SharePoint/sp-dev-build-extensions#25]
## Category

- [ ] Question
- [ ] Bug
- [x] Enhancement

## Authors

@baywet 
@VesaJuvonen 

## Expected or Desired Behavior

I cloned this repository to my Azure DevOps tenant and started to work on it. The gulp build tasks points directly to "gulpfile.js". This means that the gulp file is expected in the same folder as the where the agent is running. I think this repository will be mostly cloned and used as is for first tryouts. Meaning, the path would not map the repository. It would be better if the exported build definition would point to the folder relative to this repository.

This would be then: samples/azure-devops-ci-cd-spfx/gulpfile.js

Instead of the following setting

![image](https://user-images.githubusercontent.com/7256168/47609023-b9cbd580-da37-11e8-8d30-8bab66616995.png)

Of course you could write that in a tutorial. But if we would agree on a path relative to this repository, it would make it easier for everybody to get started with.

I got this repository and if you would agree to deep link into the folder, then I would create a pull request to change that. I have also other improvements in place to the pipeline that I would commit.

Also a step by step guideline for build & release.

## Observed Behavior

The build definition would fail instantly, if everything else is correct except the path.

## Steps to Reproduce

1. Clone the repository as is in your Azure DevOps tenant
2. Import the json build definition
3. prepare everything except the path of the gulp
4. run the build and it will fail

![image](https://user-images.githubusercontent.com/7256168/47609082-aa995780-da38-11e8-8579-d8229f48428f.png)

**Comment by baywet** [comment]
Hi @sebastianschuetze
Thanks for the feedback!
For the tutorial there's already a PR waiting for Vesa to approve to be part of the official documentation here https://github.com/SharePoint/sp-dev-docs/pull/2549
For the path thing, I think it's good to keep paths relative to the sample folder, to be consistent with what's done in the sample webparts.
The goal of the repository on the long term is to have samples for many ci cd infrastructures.
What do you think?
Also if you had time to review the PR for the documentation and provide feedback that'd be appreciated.

**Comment by SebastianSchuetze** [comment]
Hi @baywet 
I will do. But your argument makes sense. I still have some small improvements I gonna want to commit.
I would like to review your pull request, but somehow I have a hard time to find out, how I can clone your pull request. That is a bit off-topic but I am not finding an answer on github documentation

**Comment by baywet** [comment]
So if you want to be able to make modifications to my pull requests there are technically 2 ways as far as I know:
- Either I give you permissions on my fork and you commit there
- Or you fork my fork, and make your modifications in your fork, then PR to my fork if the original PR hasn't been approved yet or PR to the original repos if my PR has been approved.

I'd suggest the second approach as we're not in control of when my PR will be approved. Let me know if you need help with anything.

**Comment by SebastianSchuetze** [comment]
Okay then I will fork yours and make pull requests. Does this mean you would be able to integrate that in your current PR without creating a new one?

**Comment by baywet** [comment]
as long as you PR from/to this branch yep it should be good https://github.com/baywet/sp-dev-docs/tree/feature/VSTSCICD

**Comment by SebastianSchuetze** [comment]
Also update on my site. I checked the initial problem and suddenly the same pipeline worked like a charm even on my private build agent. So not sure what the problem was...

My improvement is the PR I am doing. So I will reference it then.

**Comment by baywet** [comment]
now that the original issue (gulp) has been resolved and that the additions you wanted to add are merged, maybe you could close this issue? Thanks for all the discussions and the contributions!
