### ISSUE TITLE
upload-app-pkg CI not working

### ISSUE THREAD

**Issue by pedropablo** [SharePoint/sp-dev-build-extensions#5]
Hello!

I configured the gulp tasks for a CI setup with VSTS (as show in the pnp video). But the webpart never get refreshed, keeps pointing to old js hashes. I have to delete the app package, run the release, then go and implement the app again, then it works.

Are there some other steps to be automatized for this to work? I see posible to delete the app first, before uploading again. But that implement action seems quite hard to script.

Any comments on this?

**Comment by estruyf** [comment]
Indeed, something changed in the App Catalog. At the moment you have to manually deploy the app again once uploaded. You do not have to delete the app. Select it and click on the deploy action and redeploy it, that should do the trick. Will check if this can also be automated.

**Comment by ahollandusc** [comment]
I'm having issues with this also and have to manually drop the new package file into the target app catalog.
Its not something to do with [Tenant Scoped Deployment](https://dev.office.com/sharepoint/docs/spfx/tenant-scoped-deployment) changes is it @estruyf ?

**Comment by estruyf** [comment]
Nope, that doesn't change it. The thing is when you upload (manually or automatically) the package file to the app catalog. The newest version will not be deployed yet. For that, you need a trigger. Which you automatically get proposed by SharePoint when you manually upload it. Now when you do it via the gulp task, it will not be done and you have to go to the app catalog site, select the file and deploy it.

Now of course in a fully automated build and release cycle, this is not an ideal situation. Last week I work on a new node package that can automate the last part. You can check it out here: [node-sppkg-deploy](https://github.com/estruyf/node-sppkg-deploy), and it is also available via npm here [https://www.npmjs.com/package/node-sppkg-deploy](https://www.npmjs.com/package/node-sppkg-deploy).

At the bottom of the page, you can see an example of the Gulp task that you can implement in your SPFx project. I will also add this task to the repo.

**Comment by estruyf** [comment]
The task has been added to the repo: [deploy-app-package](https://github.com/SharePoint/sp-dev-build-extensions/tree/master/gulp-tasks/deploy-app-package).

**Comment by ahollandusc** [comment]
Works a treat - thanks @estruyf

**Comment by pedropablo** [comment]
I'm on vacation right now but I'll try this first thing next week :)  thanks a lot @estryuf !!

**Comment by VesaJuvonen** [comment]
Closing this one, since based on input from @ahollandusc, things should be now fine. If that's not the case, let's reopen.
