### ISSUE TITLE
typo in file name for gupfile-upload-to-sharepoint.js

### ISSUE THREAD

**Issue by ahollandusc** [SharePoint/sp-dev-build-extensions#6]
gupfile-upload-to-sharepoint.js should be gulpfile-upload-to-sharepoint.js

This file is named incorrectly and results in 
[10:00:50] Error - Unknown
 Cannot find module './gulpfile-upload-to-sharepoint'
When trying to use it. I didn't actually see the typo for a while and was wondering what was wrong with my nodeJs setup.

**Comment by estruyf** [comment]
Great catch! I will update it right away. Thanks.

**Comment by VesaJuvonen** [comment]
Closing this now that the fix has been merged with PR #7. Thx @ahollandusc for reporting.

**Comment by ahollandusc** [comment]
Thanks guys :)
